# Generated by Django 6.0 on 2025-12-28 17:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('arch', models.CharField(choices=[('resnet18', 'ResNet18'), ('effnet_b0', 'EfficientNet-B0'), ('mlp', 'MLP')], max_length=32)),
                ('version', models.CharField(default='v1', max_length=40)),
                ('description', models.TextField(blank=True, default='')),
                ('file', models.FileField(upload_to='models/')),
                ('enabled', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InferenceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='web', max_length=32)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.mlmodel')),
            ],
        ),
        migrations.AddIndex(
            model_name='mlmodel',
            index=models.Index(fields=['enabled'], name='api_mlmodel_enabled_44cb9f_idx'),
        ),
        migrations.AddIndex(
            model_name='mlmodel',
            index=models.Index(fields=['is_active'], name='api_mlmodel_is_acti_4eed88_idx'),
        ),
        migrations.AddIndex(
            model_name='mlmodel',
            index=models.Index(fields=['arch'], name='api_mlmodel_arch_e0fb17_idx'),
        ),
        migrations.AddIndex(
            model_name='inferenceevent',
            index=models.Index(fields=['created_at'], name='api_inferen_created_dd1ffc_idx'),
        ),
    ]
